<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DEMON-PC" failures="1" tests="2" name="Test" time="21.343" errors="0" timestamp="2024-09-10T10:41:57 IST">
  <testcase classname="testCases.TC001_LoginTest" name="loginApp" time="3.065"/>
  <testcase classname="testCases.ErrorValidationTest" name="LoginErrorValidation" time="3.196">
    <failure type="java.lang.AssertionError" message="did not expect [Invalid credentials] but found [Invalid credentials]">
      <![CDATA[java.lang.AssertionError: did not expect [Invalid credentials] but found [Invalid credentials]
at testCases.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
</testsuite> <!-- Test -->
